//<auto-generated>
//
//</auto-generated>
namespace EzHms.ModelEntity
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    /// <summary>
    /// esfsfd ddggz gdxgdg dfdgdg
    /// </summary>
    /// <remarks></remarks>
    public class PatientRegistration : Patient
    {
        private int id = 0;
        private int session_id = 0;
        private string code = string.Empty;
        private string desc = string.Empty;
        private string name = string.Empty;

        public int ID
        {
            get
            {
                return id;
            }
            set
            {
                id = value;
            }
        }
        public string CODE
        {
            get
            {
                return code;
            }
            set
            {
                code = value;
            }
        }
        public string DESC
        {
            get
            {
                return desc;
            }
            set
            {
                desc = value;
            }
        }
        public string NAME
        {
            get
            {
                return name;
            }
            set
            {
                name = value;
            }
        }
        private string is_old;

        public string IS_OLD
        {
            get { return is_old; }
            set { is_old = value; }
        }
        private string concession_authorization_name;

        public string CONCESSION_AUTHORIZATION_NAME
        {
            get { return concession_authorization_name; }
            set { concession_authorization_name = value; }
        }
        private string due_authorization_name;

        public string DUE_AUTHORIZATION_NAME
        {
            get { return due_authorization_name; }
            set { due_authorization_name = value; }
        }
        private string doctor_department_name;

        public string DOCTOR_DEPARTMENT_NAME
        {
            get { return doctor_department_name; }
            set { doctor_department_name = value; }
        }
        private string referal_type_name;

        public string REFERAL_TYPE_NAME
        {
            get { return referal_type_name; }
            set { referal_type_name = value; }
        }
        private string pre_admn_status;

        public string PRE_ADMN_STATUS
        {
            get { return pre_admn_status; }
            set { pre_admn_status = value; }
        }




        private string is_senior_citizen;
        public string IS_SENIOR_CITIZEN
        {
            get { return is_senior_citizen; }
            set { is_senior_citizen = value; }

        }

        private string org_name;

        public string ORG_NAME
        {
            get { return org_name; }
            set { org_name = value; }
        }
        private float gross_amount;

        public float GROSS_AMOUNT
        {
            get { return gross_amount; }
            set { gross_amount = value; }
        }
        private string quick_reg;

        public string QUICK_REG
        {
            get { return quick_reg; }
            set { quick_reg = value; }
        }
        private string is_newborn;
        public string IS_NEWBORN
        {
            get { return is_newborn; }
            set { is_newborn = value; }
        }
        private string is_vip;
        public string IS_VIP
        {
            get { return is_vip; }
            set { is_vip = value; }
        }
        private string _text;

        public string Text
        {
            get { return _text; }
            set { _text = value; }
        }
        private string _value;

        public string Value
        {
            get { return _value; }
            set { _value = value; }
        }
        private int displaypr_namepr_id;

        public int Displaypr_namepr_id
        {
            get { return displaypr_namepr_id; }
            set { displaypr_namepr_id = value; }
        }
        private int pre_rev_no;

        public int PRE_REV_NO
        {
            get { return pre_rev_no; }
            set { pre_rev_no = value; }
        }
        private string pre_reg_no;

        public string PRE_REG_NO
        {
            get { return pre_reg_no; }
            set { pre_reg_no = value; }
        }

        private string mode_of_comm;
        public string MODE_OF_COMM
        {
            get { return mode_of_comm; }
            set { mode_of_comm = value; }
        }
        private string pinzipcode;

        public string PINZIPCODE
        {
            get { return pinzipcode; }
            set { pinzipcode = value; }
        }
        private string mother_name;

        public string MOTHER_NAME
        {
            get { return mother_name; }
            set { mother_name = value; }
        }

        private int refferedpr_bypr;

        public int Refferedpr_bypr
        {
            get { return refferedpr_bypr; }
            set { refferedpr_bypr = value; }
        }
        private int ethnicitypr_id;

        public int Ethnicitypr_id
        {
            get { return ethnicitypr_id; }
            set { ethnicitypr_id = value; }
        }
        private int educationpr_id;

        public int Educationpr_id
        {
            get { return educationpr_id; }
            set { educationpr_id = value; }
        }
        private int relegionpr_id;

        public int RELEGIONPR_ID
        {
            get { return relegionpr_id; }
            set { relegionpr_id = value; }
        }

        private string alias_name;

        public string ALIAS_NAME
        {
            get { return alias_name; }
            set { alias_name = value; }
        }

        private int companypr_id;

        public int COMPANYPR_ID
        {
            get { return companypr_id; }
            set { companypr_id = value; }
        }

        private int tit_id;

        public int TIT_ID
        {
            get { return tit_id; }
            set { tit_id = value; }
        }
        private int blood_id;

        public int BLOOD_ID
        {
            get { return blood_id; }
            set { blood_id = value; }
        }
        private int countrypr_id;

        public int COUNTRYPR_ID
        {
            get { return countrypr_id; }
            set { countrypr_id = value; }
        }

        private int statepr_id;

        public int STATEPR_ID
        {
            get { return statepr_id; }
            set { statepr_id = value; }
        }

        private int citypr_id;

        public int CITYPR_ID
        {
            get { return citypr_id; }
            set { citypr_id = value; }
        }
        private int areapr_id;

        public int AREAPR_ID
        {
            get { return areapr_id; }
            set { areapr_id = value; }
        }

        private int maritalpr_statuspr_id;

        public int MARITALPR_STATUSPR_ID
        {
            get { return maritalpr_statuspr_id; }
            set { maritalpr_statuspr_id = value; }
        }



        private int genderpr_id;

        public int GENDERPR_ID
        {
            get { return genderpr_id; }
            set { genderpr_id = value; }
        }







        private string pre_reg_dt;
        public string PRE_REG_DT
        {
            get { return pre_reg_dt; }
            set { pre_reg_dt = value; }
        }

        private int pre_reg_id;
        public int PRE_REG_ID
        {
            get { return pre_reg_id; }
            set { pre_reg_id = value; }
        }
        private int _reg_id = 0;

        public int REG_ID
        {
            get { return _reg_id; }
            set { _reg_id = value; }
        }

        private string _company_cd = string.Empty;

        public string COMPANY_CD
        {
            get { return _company_cd; }
            set { _company_cd = value; }
        }
        private string _relationship_id = string.Empty;

        public string RELATIONSHIP_ID
        {
            get { return _relationship_id; }
            set { _relationship_id = value; }
        }


        private string _relation_ship_name = string.Empty;

        public string RELATION_SHIP_NAME
        {
            get { return _relation_ship_name; }
            set { _relation_ship_name = value; }
        }


        private string _rel_mobile_phone = string.Empty;

        public string REL_MOBILE_PHONE
        {
            get { return _rel_mobile_phone; }
            set { _rel_mobile_phone = value; }
        }


        private string _rel_home_phone = string.Empty;

        public string REL_HOME_PHONE
        {
            get { return _rel_home_phone; }
            set { _rel_home_phone = value; }
        }

        private string _relation_address = string.Empty;

        public string RELATION_ADDRESS
        {
            get { return _relation_address; }
            set { _relation_address = value; }
        }




        private int _corp_admnren_id = 0;
        public int CORP_ADMNREN_ID
        {
            get { return _corp_admnren_id; }
            set { _corp_admnren_id = value; }
        }

        private int _emp_relationship_id = 0;
        public int EMP_RELATIONSHIP_ID
        {
            get { return _emp_relationship_id; }
            set { _emp_relationship_id = value; }
        }

        private string _salary = string.Empty;

        public string SALARY
        {
            get { return _salary; }
            set { _salary = value; }
        }

        private string _designation = string.Empty;
        public string DESIGNATION
        {
            get { return _designation; }
            set { _designation = value; }
        }


        private int _patient_class_id = 0;
        public int PATIENT_CLASS_ID
        {
            get { return _patient_class_id; }
            set { _patient_class_id = value; }
        }
        private int _bed_status_id = 0;
        public int BED_STATUS_ID
        {
            get { return _bed_status_id; }
            set { _bed_status_id = value; }
        }

        private string _referal_letter_no = string.Empty;
        public string REFERAL_LETTER_NO
        {
            get { return _referal_letter_no; }
            set { _referal_letter_no = value; }
        }

        private string _dschrg_status = string.Empty;

        public string DSCHRG_STATUS
        {
            get { return _dschrg_status; }
            set { _dschrg_status = value; }
        }

        private string _bed_status_name = string.Empty;

        public string BED_STATUS_NAME
        {
            get { return _bed_status_name; }
            set { _bed_status_name = value; }
        }


        private string _referal_letter_date = string.Empty;

        public string REFERAL_LETTER_DT
        {
            get { return _referal_letter_date; }
            set { _referal_letter_date = value; }
        }

        private int _no_of_visits_doctor_day = 0;
        public int NO_OF_VISITS_DOCTOR_DAY
        {
            get { return _no_of_visits_doctor_day; }
            set { _no_of_visits_doctor_day = value; }

        }


        private int _no_visits_day = 0;
        public int NO_VISITS_DAY
        {
            get { return _no_visits_day; }
            set { _no_visits_day = value; }
        }




        private int _p_d_no_of_visits = 0;
        public int P_D_NO_VISITS
        {
            get { return _p_d_no_of_visits; }
            set { _p_d_no_of_visits = value; }
        }

        private int _p_no_of_visits = 0;
        public int P_NO_VISITS
        {
            get { return _p_no_of_visits; }
            set { _p_no_of_visits = value; }
        }




        private string _bed_status_cd;

        public string BED_STATUS_CD
        {
            get { return _bed_status_cd; }
            set { _bed_status_cd = value; }
        }


        private int _nurse_station_id = 0;

        public int NURSE_STATION_ID
        {
            get { return _nurse_station_id; }
            set { _nurse_station_id = value; }
        }

        private string _bed_cd;

        public string BED_CD
        {
            get { return _bed_cd; }
            set { _bed_cd = value; }
        }

        private string _FLAG;

        public string FLAG
        {
            get { return _FLAG; }
            set { _FLAG = value; }
        }
        private string _APMNT_PAT_ID;

        public string APMNT_PAT_ID
        {
            get { return _APMNT_PAT_ID; }
            set { _APMNT_PAT_ID = value; }
        }
        /// <summary>
        /// df rtdvxxcv xcvvx
        /// </summary>
        ///
        private string _WARD_CREDIT_LIMIT;
        public string WARD_CREDIT_LIMIT
        {
            get { return _WARD_CREDIT_LIMIT; }
            set { _WARD_CREDIT_LIMIT = value; }
        }
        private string umr_lock;
        public string UMR_LOCK
        {
            get { return umr_lock; }
            set { umr_lock = value; }
        }
        private int _referal_id;

        public int REFERAL_ID
        {
            get { return _referal_id; }
            set { _referal_id = value; }
        }
        private int _CONCESSION_AUTH_ID;

        public int CONCESSION_AUTH_ID
        {
            get { return _CONCESSION_AUTH_ID; }
            set { _CONCESSION_AUTH_ID = value; }
        }
        private string _DESCRIPTION;
        public string DESCRIPTION
        {
            get { return _DESCRIPTION; }
            set { _DESCRIPTION = value; }
        }

        private int transaction_id;
        public int TRANSACTION_ID
        {
            get { return transaction_id; }
            set { transaction_id = value; }
        }

        private int fo_recpay_rev_no;
        public int FO_RECPAY_REV_NO
        {
            get { return fo_recpay_rev_no; }
            set { fo_recpay_rev_no = value; }
        }

        private string no_of_hosp_visits;
        public string HOSPITAL_VISITS
        {
            get { return no_of_hosp_visits; }
            set { no_of_hosp_visits = value; }
        }

        private string _CONCESSION_AUTH_NAME;
        public string CONCESSION_AUTH_NAME
        {
            get { return _CONCESSION_AUTH_NAME; }
            set { _CONCESSION_AUTH_NAME = value; }
        }
        private string _CONS_AUTH_NAME;
        public string CONS_AUTH_NAME
        {
            get { return _CONS_AUTH_NAME; }
            set { _CONS_AUTH_NAME = value; }
        }

        private string _LOCK_STATUS;
        public string LOCK_STATUS
        {
            get { return _LOCK_STATUS; }
            set { _LOCK_STATUS = value; }
        }

        private int _Admn_ID;
        public int ADMN_ID
        {
            get { return _Admn_ID; }
            set { _Admn_ID = value; }
        }

        private int _DUE_AUTH_ID;
        public int DUE_AUTH_ID
        {
            get { return _DUE_AUTH_ID; }
            set { _DUE_AUTH_ID = value; }
        }
        private int _vendor_id;
        public int VENDOR_ID
        {
            get { return _vendor_id; }
            set { _vendor_id = value; }
        }

        private string _DUE_AUTH;
        public string DUE_AUTH
        {
            get { return _DUE_AUTH; }
            set { _DUE_AUTH = value; }
        }
        private string _status;
        public string STATUS
        {
            get { return _status; }
            set { _status = value; }
        }
        private int _REFERAL_TYPE_ID;

        public int REFERAL_TYPE_ID
        {
            get { return _REFERAL_TYPE_ID; }
            set { _REFERAL_TYPE_ID = value; }
        }
        private string _REFERAL_TYPE;

        public string REFERAL_TYPE
        {
            get { return _REFERAL_TYPE; }
            set { _REFERAL_TYPE = value; }
        }
        private string _REFERAL_NAME;

        public string REFERAL_NAME
        {
            get { return _REFERAL_NAME; }
            set { _REFERAL_NAME = value; }
        }
        private int _REFERAL_DOCTOR_ID;

        public int REFERAL_DOCTOR_ID
        {
            get { return _REFERAL_DOCTOR_ID; }
            set { _REFERAL_DOCTOR_ID = value; }
        }

        private int _BILL_ID;

        public int BILL_ID
        {
            get { return _BILL_ID; }
            set { _BILL_ID = value; }
        }


        private string _CONCESSION_AMOUNT;

        public string CONCESSION_AMOUNT
        {
            get { return _CONCESSION_AMOUNT; }
            set { _CONCESSION_AMOUNT = value; }
        }

        private string _BILL_SRV_AMOUNT;

        public string BILL_SRV_AMOUNT
        {
            get { return _BILL_SRV_AMOUNT; }
            set { _BILL_SRV_AMOUNT = value; }
        }

        private string _CANCEL_AMOUNT;

        public string CANCEL_AMOUNT
        {
            get { return _CANCEL_AMOUNT; }
            set { _CANCEL_AMOUNT = value; }
        }
        private int _ORDR_DOCTOR_ID;

        public int ORDR_DOCTOR_ID
        {
            get { return _ORDR_DOCTOR_ID; }
            set { _ORDR_DOCTOR_ID = value; }
        }
        private int _bed_id;
        public int BED_ID
        {
            set { _bed_id = value; }
            get { return _bed_id; }
        }
        private int _room_id;
        public int ROOM_ID
        {
            set { _room_id = value; }
            get { return _room_id; }
        }
        private int _ward_group_id;
        public int WARD_GROUP_ID
        {
            set { _ward_group_id = value; }
            get { return _ward_group_id; }
        }

        private string _ward_group_name;
        public string WARD_GROUP_NAME
        {
            set { _ward_group_name = value; }
            get { return _ward_group_name; }
        }
        private int _treated_ward_group_id;
        public int TREATED_WARD_GROUP_ID
        {
            set { _treated_ward_group_id = value; }
            get { return _treated_ward_group_id; }
        }

        private string _treated_ward_group_name;
        public string TREATED_WARD_GROUP_NAME
        {
            set { _treated_ward_group_name = value; }
            get { return _treated_ward_group_name; }
        }

        private int _ward_id;
        public int WARD_ID
        {
            set { _ward_id = value; }
            get { return _ward_id; }
        }

        private int _credit_org_id;
        public int CREDIT_ORG_ID
        {
            set { _credit_org_id = value; }
            get { return _credit_org_id; }
        }
        private string company_name;

        public string COMPANY_NAME
        {
            get { return company_name; }
            set { company_name = value; }
        }
        private bool _vip_flag;
        public bool VIP
        {
            get
            {
                return _vip_flag;
            }
            set
            {
                _vip_flag = value;
            }
        }
        private bool _new_born;
        public bool NEWBORN
        {
            get
            {
                return _new_born;
            }
            set
            {
                _new_born = value;
            }
        }

        private string _ordered_dt = string.Empty;
        public string ORDERED_DT
        {
            get
            {
                return _ordered_dt;
            }
            set
            {
                _ordered_dt = value;
            }
        }
        private string _SERVICE_GROUP_ID = string.Empty;
        private string _SERVICE_GROUP_NAME = string.Empty;

        private string umr_no = string.Empty;
        private string _registration_dt;
        private string isnewregistration;
        private string _registration_id;
        private string registration_no = string.Empty;
        private string reg_expiry_dt = string.Empty;
        private string registration_fee;
        private string _reference_source_id;
        private string referencesourcename;
        private string referralphone;
        private string referraladdr;
        private string _referred_by;
        private int referal_id;
        private string _referred_doctor_type_id;
        private string consultant;
        private string _referrend_doctor_id;//Consultant
        private string _receipt_no;
        private string occupation;
        private string occupation_id;
        private string iscentralized;
        private string employee_id;
        private string quantity_id;
        private string service_id;
        private string concession_mode_id;
        private string religion;
        private string diet_type;
        private string ethnicity;
        private int count;
        private string transaction_no;
        private string transaction_dt;
        private string bill_dt;
        private string bill_no;
        private string admn_no;
        private string admn_dt;
        private string ward_name;
        private string room_name;
        private string bed_name;
        private string corporate_name;

        private string _IS_REFERAL = string.Empty;

        public string IS_REFERAL
        {
            get { return _IS_REFERAL; }
            set { _IS_REFERAL = value; }
        }

        public string CORPORATE_NAME
        {
            get { return corporate_name; }
            set { corporate_name = value; }
        }

        public string BED_NAME
        {
            get { return bed_name; }
            set { bed_name = value; }
        }

        public string ROOM_NAME
        {
            get { return room_name; }
            set { room_name = value; }
        }

        public string WARD_NAME
        {
            get { return ward_name; }
            set { ward_name = value; }
        }

        public string ADMN_DT
        {
            get { return admn_dt; }
            set { admn_dt = value; }
        }

        public string ADMN_NO
        {
            get { return admn_no; }
            set { admn_no = value; }
        }

        public string BILL_NO
        {
            get { return bill_no; }
            set { bill_no = value; }
        }
        private string transaction_type;
        private float trans_amount;
        private float bill_amount;
        private float paid_amount;
        private float due_amount;
        private float concession;
        private float net_amount;
        private string transaction_by;

        private string _dosage_qty;
        private string _specimenname;
        private string _vacctainername;
        private string _precautions;
        private string _clinical_history;
        private string _servicename;
        private int _serviceid;
        private int _specimen_id;
        private int _specimen_rev_id;
        private int _vaccutainer_id;
        private string _gendername;
        private string _consultantname;
        private string _patname;
        private string _father_name;
        private string _consultetionno;
        private string _regno;
        private string _visit_type;
        private string _mobno;
        private string _consultation_dt;
        private string _fromdt;
        private string _todate;
        public string SERVICE_GROUP_ID
        {
            get { return _SERVICE_GROUP_ID; }
            set { _SERVICE_GROUP_ID = value; }
        }
        public string SERVICE_GROUP_NAME
        {
            get { return _SERVICE_GROUP_NAME; }
            set { _SERVICE_GROUP_NAME = value; }
        }
        public string FROM_DATE
        {
            get { return _fromdt; }
            set { _fromdt = value; }
        }
        public string TO_DATE
        {
            get { return _todate; }
            set { _todate = value; }
        }
        public string CONSULTATION_DT
        {
            get { return _consultation_dt; }
            set { _consultation_dt = value; }
        }

        public string MOBILE_NO
        {
            get { return _mobno; }
            set { _mobno = value; }
        }
        public string VISIT_TYPE
        {
            get { return _visit_type; }
            set { _visit_type = value; }
        }
        public string REGNO
        {
            get { return _regno; }
            set { _regno = value; }
        }
        public string CONSULTETION_NO
        {
            get { return _consultetionno; }
            set { _consultetionno = value; }
        }

        public string PAT_NAME
        {
            get { return _patname; }
            set { _patname = value; }
        }
        public string FATHER_NAME
        {
            get { return _father_name; }
            set { _father_name = value; }
        }


        public float DUE_AMOUNT
        {
            get { return due_amount; }
            set { due_amount = value; }
        }

        public float NET_AMOUNT
        {
            get { return net_amount; }
            set { net_amount = value; }
        }

        public float CONCESSION
        {
            get { return concession; }
            set { concession = value; }
        }

        /// <summary>
        /// Gets or sets the UM r_ NO.
        /// </summary>
        /// <value>The UM r_ NO.</value>
        /// <remarks></remarks>
        public string UMR_NO
        {
            get
            {
                return umr_no;
            }
            set
            {
                umr_no = value;
            }
        }

        /// <summary>
        /// Gets or sets the REGISTRATIO n_ DT.
        /// </summary>
        /// <value>The REGISTRATIO n_ DT.</value>
        /// <remarks></remarks>
        public string REGISTRATION_DT
        {
            set { _registration_dt = value; }
            get { return _registration_dt; }
        }

        /// <summary>
        /// Gets or sets the ISNEWREGISTRATION.
        /// </summary>
        /// <value>The ISNEWREGISTRATION.</value>
        /// <remarks></remarks>
        public string ISNEWREGISTRATION
        {
            set { isnewregistration = value; }
            get { return isnewregistration; }
        }

        /// <summary>
        /// Gets or sets the REGISTRATIO n_ ID.
        /// </summary>
        /// <value>The REGISTRATIO n_ ID.</value>
        /// <remarks></remarks>
        public string REGISTRATION_ID
        {
            set { _registration_id = value; }
            get { return _registration_id; }
        }

        /// <summary>
        /// Gets or sets the REGISTRATIO n_ NO.
        /// </summary>
        /// <value>The REGISTRATIO n_ NO.</value>
        /// <remarks></remarks>
        public string REGISTRATION_NO
        {
            set { registration_no = value; }
            get { return registration_no; }
        }
        public string REG_NO
        {
            set { registration_no = value; }
            get { return registration_no; }
        }

        public string REG_EXPIRY_DT
        {
            set { reg_expiry_dt = value; }
            get { return reg_expiry_dt; }
        }
        /// <summary>
        /// Gets or sets the REGISTRATIO n_ FEE.
        /// </summary>
        /// <value>The REGISTRATIO n_ FEE.</value>
        /// <remarks></remarks>
        public string REGISTRATION_FEE
        {
            set { registration_fee = value; }
            get { return registration_fee; }
        }

        /// <summary>
        /// Gets or sets the REFERENC e_ SOURC e_ ID.
        /// </summary>
        /// <value>The REFERENC e_ SOURC e_ ID.</value>
        /// <remarks></remarks>
        public string REFERENCE_SOURCE_ID
        {
            set { _reference_source_id = value; }
            get { return _reference_source_id; }
        }

        /// <summary>
        /// Gets or sets the REFERENC e_ SOURCENAME.
        /// </summary>
        /// <value>The REFERENC e_ SOURCENAME.</value>
        /// <remarks></remarks>
        public string REFERENCE_SOURCENAME
        {
            get { return referencesourcename; }
            set { referencesourcename = value; }
        }

        /// <summary>
        /// Gets or sets the referral phone.
        /// </summary>
        /// <value>The referral phone.</value>
        /// <remarks></remarks>
        public string REFERRALPHONE
        {
            get { return referralphone; }
            set { referralphone = value; }
        }

        /// <summary>
        /// Gets or sets the referral address.
        /// </summary>
        /// <value>The referral address.</value>
        /// <remarks></remarks>
        public string REFERRALADDRESS
        {
            get { return referraladdr; }
            set { referraladdr = value; }
        }

        /// <summary>
        /// Gets or sets the REFERRE d_ BY.
        /// </summary>
        /// <value>The REFERRE d_ BY.</value>
        /// <remarks></remarks>
        public string REFERRED_BY
        {
            set { _referred_by = value; }
            get { return _referred_by; }
        }

        /// <summary>
        /// Gets or sets the REFERRE d_ DOCTO r_ TYP e_ ID.
        /// </summary>
        /// <value>The REFERRE d_ DOCTO r_ TYP e_ ID.</value>
        /// <remarks></remarks>
        public string REFERRED_DOCTOR_TYPE_ID
        {
            set { _referred_doctor_type_id = value; }
            get { return _referred_doctor_type_id; }
        }

        /// <summary>
        /// Gets or sets the CONSULTANT.
        /// </summary>
        /// <value>The CONSULTANT.</value>
        /// <remarks></remarks>
        public string CONSULTANT
        {
            get { return consultant; }
            set { consultant = value; }
        }

        /// <summary>
        /// Gets or sets the REFERREN d_ DOCTO r_ ID.
        /// </summary>
        /// <value>The REFERREN d_ DOCTO r_ ID.</value>
        /// <remarks></remarks>
        public string REFERREND_DOCTOR_ID
        {
            set { _referrend_doctor_id = value; }
            get { return _referrend_doctor_id; }
        }

        /// <summary>
        /// Gets or sets the RECEIP t_ NO.
        /// </summary>
        /// <value>The RECEIP t_ NO.</value>
        /// <remarks></remarks>
        public string RECEIPT_NO
        {
            set { _receipt_no = value; }
            get { return _receipt_no; }
        }

        /// <summary>
        /// Gets or sets the OCCUPATION.
        /// </summary>
        /// <value>The OCCUPATION.</value>
        /// <remarks></remarks>
        public string OCCUPATION
        {
            set { occupation = value; }
            get { return occupation; }
        }

        /// <summary>
        /// Gets or sets the OCCUPATIO n_ ID.
        /// </summary>
        /// <value>The OCCUPATIO n_ ID.</value>
        /// <remarks></remarks>
        public string OCCUPATION_ID
        {
            set { occupation_id = value; }
            get { return occupation_id; }
        }

        /// <summary>
        /// Gets or sets the ISCENTRALIZED.
        /// </summary>
        /// <value>The ISCENTRALIZED.</value>
        /// <remarks></remarks>
        public string ISCENTRALIZED
        {
            set { iscentralized = value; }
            get { return iscentralized; }
        }

        /// <summary>
        /// Gets or sets the EMPLOYE e_ ID.
        /// </summary>
        /// <value>The EMPLOYE e_ ID.</value>
        /// <remarks></remarks>
        public string EMPLOYEE_ID
        {
            set { employee_id = value; }
            get { return employee_id; }
        }

        private string emp_name;
        public string EMP_NAME
        {
            set { emp_name = value; }
            get { return emp_name; }

        }
        private string card_validity;
        public string CARD_VALIDITY
        {
            set { card_validity = value; }
            get { return card_validity; }

        }
        private string _CREDIT_LIMIT_AMT;
        public string CREDIT_LIMIT_AMT
        {
            get { return _CREDIT_LIMIT_AMT; }
            set { _CREDIT_LIMIT_AMT = value; }
        }
        private string card_no;
        public string CARD_NO
        {
            set { card_no = value; }
            get { return card_no; }

        }
        /// <summary>
        /// Gets or sets the QUANTIT y_ ID.
        /// </summary>
        /// <value>The QUANTIT y_ ID.</value>
        /// <remarks></remarks>
        public string QUANTITY_ID
        {
            set { quantity_id = value; }
            get { return quantity_id; }
        }

        /// <summary>
        /// Gets or sets the SERVIC e_ ID.
        /// </summary>
        /// <value>The SERVIC e_ ID.</value>
        /// <remarks></remarks>
        public string SERVICE_ID
        {
            set { service_id = value; }
            get { return service_id; }
        }

        /// <summary>
        /// Gets or sets the CONCESSIO n_ MOD e_ ID.
        /// </summary>
        /// <value>The CONCESSIO n_ MOD e_ ID.</value>
        /// <remarks></remarks>
        public string CONCESSION_MODE_ID
        {
            set { concession_mode_id = value; }
            get { return concession_mode_id; }
        }

        /// <summary>
        /// Gets or sets the RELIGION.
        /// </summary>
        /// <value>The RELIGION.</value>
        /// <remarks></remarks>
        public string RELIGION
        {
            set { religion = value; }
            get { return religion; }
        }

        /// <summary>
        /// Gets or sets the DIE t_ TYPE.
        /// </summary>
        /// <value>The DIE t_ TYPE.</value>
        /// <remarks></remarks>
        public string DIET_TYPE
        {
            set { diet_type = value; }
            get { return diet_type; }
        }

        /// <summary>
        /// Gets or sets the ETHNICITY.
        /// </summary>
        /// <value>The ETHNICITY.</value>
        /// <remarks></remarks>
        public string ETHNICITY
        {
            set { ethnicity = value; }
            get { return ethnicity; }
        }

        /// <summary>
        /// Gets or sets the count.
        /// </summary>
        /// <value>The count.</value>
        /// <remarks></remarks>
        public int Count
        {
            get { return count; }
            set { count = value; }
        }

        /// <summary>
        /// Gets or sets the transaction_no.
        /// </summary>
        /// <value>The transaction_no.</value>
        /// <remarks></remarks>
        public string Transaction_no
        {
            get { return transaction_no; }
            set { transaction_no = value; }
        }

        /// <summary>
        /// Gets or sets the transaction_dt.
        /// </summary>
        /// <value>The transaction_dt.</value>
        /// <remarks></remarks>
        public string Transaction_dt
        {
            get { return transaction_dt; }
            set { transaction_dt = value; }
        }

        /// <summary>
        /// Gets or sets the BIL l_ DT.
        /// </summary>
        /// <value>The BIL l_ DT.</value>
        /// <remarks></remarks>
        public string BILL_DT
        {
            get { return bill_dt; }
            set { bill_dt = value; }
        }

        /// <summary>
        /// Gets or sets the transaction_type.
        /// </summary>
        /// <value>The transaction_type.</value>
        /// <remarks></remarks>
        public string Transaction_type
        {
            get { return transaction_type; }
            set { transaction_type = value; }
        }

        /// <summary>
        /// Gets or sets the trans_amount.
        /// </summary>
        /// <value>The trans_amount.</value>
        /// <remarks></remarks>
        public float Trans_amount
        {
            get { return trans_amount; }
            set { trans_amount = value; }
        }

        /// <summary>
        /// Gets or sets the BIL l_ AMOUNT.
        /// </summary>
        /// <value>The BIL l_ AMOUNT.</value>
        /// <remarks></remarks>
        public float BILL_AMOUNT
        {
            get { return bill_amount; }
            set { bill_amount = value; }
        }

        /// <summary>
        /// Gets or sets the PAI d_ AMOUNT.
        /// </summary>
        /// <value>The PAI d_ AMOUNT.</value>
        /// <remarks></remarks>
        public float PAID_AMOUNT
        {
            get { return paid_amount; }
            set { paid_amount = value; }
        }
        private double _ADVANCE_AMOUNT;
        public double ADVANCE_AMOUNT
        {
            get { return _ADVANCE_AMOUNT; }
            set { _ADVANCE_AMOUNT = value; }
        }
        /// <summary>
        /// Gets or sets the transaction_by.
        /// </summary>
        /// <value>The transaction_by.</value>
        /// <remarks></remarks>
        public string Transaction_by
        {
            get { return transaction_by; }
            set { transaction_by = value; }
        }

        private string zipcode = string.Empty;
        public string ZIPCODE
        {
            get { return zipcode; }
            set { zipcode = value; }
        }
        private string address = string.Empty;
        public string ADDRESS
        {
            get { return address; }
            set { address = value; }
        }
        public string ADDRESS1
        {
            get { return address; }
            set { address = value; }
        }
        private string city = string.Empty;
        public string CITY
        {
            get { return city; }
            set { city = value; }
        }
        private string _area = string.Empty;
        public string AREA
        {
            get { return _area; }
            set { _area = value; }
        }
        private string _state = string.Empty;
        public string STATE
        {
            get { return _state; }
            set { _state = value; }
        }
        private string _district_name = string.Empty;
        public string DISTRICT_NAME
        {
            get { return _district_name; }
            set { _district_name = value; }
        }
        private string _country = string.Empty;
        public string COUNTRY
        {
            get { return _country; }
            set { _country = value; }
        }
        /// <summary>
        /// Gets or sets the DOSAG e_ QTY.
        /// </summary>
        /// <value>The DOSAG e_ QTY.</value>
        /// <remarks></remarks>
        public string DOSAGE_QTY
        {
            set { _dosage_qty = value; }
            get { return _dosage_qty; }
        }

        /// <summary>
        /// Gets or sets the specimenname.
        /// </summary>
        /// <value>The specimenname.</value>
        /// <remarks></remarks>
        public string Specimenname
        {
            set { _specimenname = value; }
            get { return _specimenname; }
        }

        /// <summary>
        /// Gets or sets the vacctainername.
        /// </summary>
        /// <value>The vacctainername.</value>
        /// <remarks></remarks>
        public string Vacctainername
        {
            set { _vacctainername = value; }
            get { return _vacctainername; }
        }

        /// <summary>
        /// Gets or sets the PRECAUTIONS.
        /// </summary>
        /// <value>The PRECAUTIONS.</value>
        /// <remarks></remarks>
        public string PRECAUTIONS
        {
            set { _precautions = value; }
            get { return _precautions; }
        }

        /// <summary>
        /// Gets or sets the CLINICA l_ HISTORY.
        /// </summary>
        /// <value>The CLINICA l_ HISTORY.</value>
        /// <remarks></remarks>
        public string CLINICAL_HISTORY
        {
            set { _clinical_history = value; }
            get { return _clinical_history; }
        }

        /// <summary>
        /// Gets or sets the servicename.
        /// </summary>
        /// <value>The servicename.</value>
        /// <remarks></remarks>
        public string Servicename
        {
            set { _servicename = value; }
            get { return _servicename; }
        }

        /// <summary>
        /// Gets or sets the service ID.
        /// </summary>
        /// <value>The service ID.</value>
        /// <remarks></remarks>
        public int ServiceID
        {
            set { _serviceid = value; }
            get { return _serviceid; }
        }

        public int REFRL_ID
        {
            get { return referal_id; }
            set { referal_id = value; }

        }
        /// <summary>
        /// Gets or sets the SPECIME n_ ID.
        /// </summary>
        /// <value>The SPECIME n_ ID.</value>
        /// <remarks></remarks>
        public int SPECIMEN_ID
        {
            set { _specimen_id = value; }
            get { return _specimen_id; }
        }

        /// <summary>
        /// Gets or sets the SPECIME n_ RE v_ ID.
        /// </summary>
        /// <value>The SPECIME n_ RE v_ ID.</value>
        /// <remarks></remarks>
        public int SPECIMEN_REV_ID
        {
            set { _specimen_rev_id = value; }
            get { return _specimen_rev_id; }
        }

        /// <summary>
        /// Gets or sets the VACCUTAINE r_ ID.
        /// </summary>
        /// <value>The VACCUTAINE r_ ID.</value>
        /// <remarks></remarks>
        public int VACCUTAINER_ID
        {
            set { _vaccutainer_id = value; }
            get { return _vaccutainer_id; }
        }

        /// <summary>
        /// Gets or sets the name of the gender.
        /// </summary>
        /// <value>The name of the gender.</value>
        /// <remarks></remarks>
        public string GenderName
        {
            set { _gendername = value; }
            get { return _gendername; }
        }

        /// <summary>
        /// Gets or sets the consultantname.
        /// </summary>
        /// <value>The consultantname.</value>
        /// <remarks></remarks>
        public string Consultantname
        {
            set { _consultantname = value; }
            get { return _consultantname; }
        }

        private string company_fee = string.Empty;
        public string COMPANY_FEE
        {
            get { return company_fee; }
            set { company_fee = value; }
        }
        private string _patient_expiry;

        public string PATIENT_EXPIRY
        {
            get { return _patient_expiry; }
            set { _patient_expiry = value; }
        }
        private string _is_blocked;

        public string IS_BLOCKED
        {
            get { return _is_blocked; }
            set { _is_blocked = value; }
        }
        private string _is_merge;

        public string IS_MERGE
        {
            get { return _is_merge; }
            set { _is_merge = value; }
        }
        private string _merge_umr_no;

        public string MERGE_UMR_NO
        {
            get { return _merge_umr_no; }
            set { _merge_umr_no = value; }
        }
        private string _OP;

        public string OP
        {
            get { return _OP; }
            set { _OP = value; }
        }
        private string _CANCEL_BY;

        public string CANCEL_BY
        {
            get { return _CANCEL_BY; }
            set { _CANCEL_BY = value; }
        }
        private string _merge_patient_id;

        public string MERGE_PATIENT_ID
        {
            get { return _merge_patient_id; }
            set { _merge_patient_id = value; }
        }
        private string _is_reg_expiry;

        public string IS_REG_EXPIRY
        {
            get { return _is_reg_expiry; }
            set { _is_reg_expiry = value; }
        }
        private string _outstanding_due;

        public string OUTSTANDING_DUE
        {
            get { return _outstanding_due; }
            set { _outstanding_due = value; }
        }
        private string _refund;

        public string REFUND
        {
            get { return _refund; }
            set { _refund = value; }
        }
        private string _expiring_amt;

        public string EXPIRING_AMT
        {
            get { return _expiring_amt; }
            set { _expiring_amt = value; }
        }
        private string _pkg_dts;

        public string PKG_DTS
        {
            get { return _pkg_dts; }
            set { _pkg_dts = value; }
        }
        private string _cncsn_rule_id;

        public string CNCSN_RULE_ID
        {
            get { return _cncsn_rule_id; }
            set { _cncsn_rule_id = value; }
        }
        private string _hc_health_card_sts;

        public string HC_HEALTH_CARD_STS
        {
            get { return _hc_health_card_sts; }
            set { _hc_health_card_sts = value; }
        }
        private string _is_assesment_required;

        public string IS_ASSESMENT_REQUIRED
        {
            get { return _is_assesment_required; }
            set { _is_assesment_required = value; }
        }
        private string _er_doc_sts;

        public string ER_DOC_STS
        {
            get { return _er_doc_sts; }
            set { _er_doc_sts = value; }
        }
        private string _mlc_status;

        public string MLC_STATUS
        {
            get { return _mlc_status; }
            set { _mlc_status = value; }
        }
        private string _slot_token_no;

        public string SLOT_TOKEN_NO
        {
            get { return _slot_token_no; }
            set { _slot_token_no = value; }
        }
        private string _event_track_id;

        public string EVENT_TRACK_ID
        {
            get { return _event_track_id; }
            set { _event_track_id = value; }
        }
        private string _health_card_no;

        public string HEALTH_CARD_NO
        {
            get { return _health_card_no; }
            set { _health_card_no = value; }
        }
        private string _questionary_id_new;

        public string QUESTIONARY_ID_NEW
        {
            get { return _questionary_id_new; }
            set { _questionary_id_new = value; }
        }
        private string transaction_ref_id;

        public string TRANSACTION_REF_ID
        {
            get { return transaction_ref_id; }
            set { transaction_ref_id = value; }
        }
        private string _is_counter_required;

        public string IS_COUNTER_REQUIRED
        {
            get { return _is_counter_required; }
            set { _is_counter_required = value; }
        }
        private string _doctor_exists;

        public string DOCTOR_EXISTS
        {
            get { return _doctor_exists; }
            set { _doctor_exists = value; }
        }
        public int DEPOSIT_STATUS_ID { get; set; }
        public string IS_SAMPLE_CANCEL { get; set; }
        private string _rec_type_name;
        public string REC_TYPE_NAME
        {
            get { return _rec_type_name; }
            set { _rec_type_name = value; }
        }
        private string _PRE_REFUND_STATUS;
        public string PRE_REFUND_STATUS
        {
            get { return _PRE_REFUND_STATUS; }
            set { _PRE_REFUND_STATUS = value; }
        }
        private string tot_record_cnt;
        public string TOT_RECORD_CNT
        {
            get { return tot_record_cnt; }
            set { tot_record_cnt = value; }
        }
        private int _Doctor_ID;

        public int Doctor_ID
        {
            get { return _Doctor_ID; }
            set { _Doctor_ID = value; }
        }
        private string company_id;
        public string COMPANY_ID
        {
            get { return company_id; }
            set { company_id = value; }
        }
        private int tariff_id;
        public int TARIFF_ID
        {
            get { return tariff_id; }
            set { tariff_id = value; }
        }
        private string doctor_cd;
        public string DOCTOR_CD
        {
            get { return doctor_cd; }
            set { doctor_cd = value; }
        }

        private string department_desc;
        public string DEPARTMENT_DESC
        {
            get { return department_desc; }
            set { department_desc = value; }
        }
        private int department_id;
        public int DEPARTMENT_ID
        {
            get { return department_id; }
            set { department_id = value; }
        }
        private string mobile_phone;
        public string MOBILE_PHONE
        {
            get { return mobile_phone; }
            set { mobile_phone = value; }
        }

        private int _DEPENDENT_ID;

        public int DEPENDENT_ID
        {
            get { return _DEPENDENT_ID; }
            set { _DEPENDENT_ID = value; }
        }

        private string rel_ship_id;
        public string REL_SHIP_ID
        {
            get { return rel_ship_id; }
            set { rel_ship_id = value; }
        }
        private string patient_relationship_name;
        public string PATIENT_RELATIONSHIP_NAME
        {
            get { return patient_relationship_name; }
            set { patient_relationship_name = value; }
        }
        private string EMPDOB;
        public string empDOB
        {
            get { return EMPDOB; }
            set { EMPDOB = value; }
        }
        private string exist;
        public string EXIST
        {
            get { return exist; }
            set { exist = value; }
        }
        private string slot1;
        public string SLOT1
        {
            get { return slot1; }
            set { slot1 = value; }
        }
        private string slot2;
        public string SLOT2
        {
            get { return slot2; }
            set { slot2 = value; }
        }
        private string slot3;
        public string SLOT3
        {
            get { return slot3; }
            set { slot3 = value; }
        }
        private string grp_bill_no;
        public string GRP_BILL_NO
        {
            get { return grp_bill_no; }
            set { grp_bill_no = value; }
        }
        private string receipt_amount;
        public string RECEIPT_AMOUNT
        {
            get { return receipt_amount; }
            set { receipt_amount = value; }
        }
        private string created_by;
        public string CREATED_BY
        {
            get { return created_by; }
            set { created_by = value; }
        }
        private string modified_by;
        public string MODIFIED_BY
        {
            get { return modified_by; }
            set { modified_by = value; }
        }
        private string authorized_name;
        public string AUTHORIZED_NAME
        {
            get { return authorized_name; }
            set { authorized_name = value; }
        }
        private string foreign_categories_name;
        public string FOREIGN_CATEGORIES_NAME
        {
            get { return foreign_categories_name; }
            set { foreign_categories_name = value; }
        }
        private string net_amt;
        public string NET_AMT
        {
            get { return net_amt; }
            set { net_amt = value; }
        }
        private string pat_gross_amount;
        public string PAT_GROSS_AMOUNT
        {
            get { return pat_gross_amount; }
            set { pat_gross_amount = value; }
        }
        private string pat_concession_amount;
        public string PAT_CONCESSION_AMOUNT
        {
            get { return pat_concession_amount; }
            set { pat_concession_amount = value; }
        }
        private string pat_net_amt;
        public string PAT_NET_AMT
        {
            get { return pat_net_amt; }
            set { pat_net_amt = value; }
        }
        private string pat_paid_amount;
        public string PAT_PAID_AMOUNT
        {
            get { return pat_paid_amount; }
            set { pat_paid_amount = value; }
        }

        private string pat_due_amount;
        public string PAT_DUE_AMOUNT
        {
            get { return pat_due_amount; }
            set { pat_due_amount = value; }
        }
        private string cmp_gross_amt;
        public string CMP_GROSS_AMT
        {
            get { return cmp_gross_amt; }
            set { cmp_gross_amt = value; }
        }
        private string cmp_paid_amt;
        public string CMP_PAID_AMT
        {
            get { return cmp_paid_amt; }
            set { cmp_paid_amt = value; }
        }
        private string company_concession_amount;
        public string COMPANY_CONCESSION_AMOUNT
        {
            get { return company_concession_amount; }
            set { company_concession_amount = value; }
        }
        private string cmp_net_amt;
        public string CMP_NET_AMT
        {
            get { return cmp_net_amt; }
            set { cmp_net_amt = value; }
        }
        private string cmp_due_amt;
        public string CMP_DUE_AMT
        {
            get { return cmp_due_amt; }
            set { cmp_due_amt = value; }
        }
        private string transfer_type_id;
        public string TRANSFER_TYPE_ID
        {
            get { return transfer_type_id; }
            set { transfer_type_id = value; }
        }
        private string company_due;
        public string COMPANY_DUE
        {
            get { return company_due; }
            set { company_due = value; }
        }
        private string dms_upload;
        public string DMS_UPLOAD
        {
            get { return dms_upload; }
            set { dms_upload = value; }
        }
        private string bill_amount_exc_gst;
        public string BILL_AMOUNT_EXC_GST
        {
            get { return bill_amount_exc_gst; }
            set { bill_amount_exc_gst = value; }
        }
        private string net_amount_exc_gst;
        public string NET_AMOUNT_EXC_GST
        {
            get { return net_amount_exc_gst; }
            set { net_amount_exc_gst = value; }
        }
        private string gst_amount;
        public string GST_AMOUNT
        {
            get { return gst_amount; }
            set { gst_amount = value; }
        }
        private string sgst_amount;
        public string SGST_AMOUNT
        {
            get { return sgst_amount; }
            set { sgst_amount = value; }
        }
        private string cgst_amount;
        public string CGST_AMOUNT
        {
            get { return cgst_amount; }
            set { cgst_amount = value; }
        }
        private string bill_type_id;
        public string BILL_TYPE_ID
        {
            get { return bill_type_id; }
            set { bill_type_id = value; }
        }
        private string patient_status;
        public string PATIENT_STATUS
        {
            get { return patient_status; }
            set { patient_status = value; }
        }
        private string pat_outstanding_due;
        public string PAT_OUTSTANDING_DUE
        {
            get { return pat_outstanding_due; }
            set { pat_outstanding_due = value; }
        }
        private string cmp_outstanding_due;
        public string CMP_OUTSTANDING_DUE
        {
            get { return cmp_outstanding_due; }
            set { cmp_outstanding_due = value; }
        }
        private string doctor_name;
        public string DOCTOR_NAME
        {
            get { return doctor_name; }
            set { doctor_name = value; }
        }
        private string doctor_id;
        public string DOCTOR_ID
        {
            get { return doctor_id; }
            set { doctor_id = value; }
        }
        private string company_amount;
        public string COMPANY_AMOUNT
        {
            get { return company_amount; }
            set { company_amount = value; }
        }
        private string company_net_amount;
        public string COMPANY_NET_AMOUNT
        {
            get { return company_net_amount; }
            set { company_net_amount = value; }
        }
        private string company_due_amount;
        public string COMPANY_DUE_AMOUNT
        {
            get { return company_due_amount; }
            set { company_due_amount = value; }
        }
        private string cash_concession_amount;
        public string CASH_CONCESSION_AMOUNT
        {
            get { return cash_concession_amount; }
            set { cash_concession_amount = value; }
        }
        private string cash_concession_pcnt;
        public string CASH_CONCESSION_PCNT
        {
            get { return cash_concession_pcnt; }
            set { cash_concession_pcnt = value; }
        }
        private string hc_concession_amount;
        public string HC_CONCESSION_AMOUNT
        {
            get { return hc_concession_amount; }
            set { hc_concession_amount = value; }
        }
        private string hc_concession_pcnt;
        public string HC_CONCESSION_PCNT
        {
            get { return hc_concession_pcnt; }
            set { hc_concession_pcnt = value; }
        }
        private string managment_concession_amount;
        public string MANAGMENT_CONCESSION_AMOUNT
        {
            get { return managment_concession_amount; }
            set { managment_concession_amount = value; }

        }
        private string managment_concession_pcnt;
        public string MANAGMENT_CONCESSION_PCNT
        {
            get { return managment_concession_pcnt; }
            set { managment_concession_pcnt = value; }
        }
        private string staff_concession_amount;
        public string STAFF_CONCESSION_AMOUNT
        {
            get { return staff_concession_amount; }
            set { staff_concession_amount = value; }
        }
        private string staff_concession_pcnt;
        public string STAFF_CONCESSION_PCNT
        {
            get { return staff_concession_pcnt; }
            set { staff_concession_pcnt = value; }
        }
        private string event_based_concession_amount;
        public string EVENT_BASED_CONCESSION_AMOUNT
        {
            get { return event_based_concession_amount; }
            set { event_based_concession_amount = value; }
        }
        private string event_based_concession_pcnt;
        public string EVENT_BASED_CONCESSION_PCNT
        {
            get { return event_based_concession_pcnt; }
            set { event_based_concession_pcnt = value; }
        }
        private string concession_rule_concession_amount;
        public string CONCESSION_RULE_CONCESSION_AMOUNT
        {
            get { return concession_rule_concession_amount; }
            set { concession_rule_concession_amount = value; }
        }
        private string concession_rule_concession_pcnt;
        public string CONCESSION_RULE_CONCESSION_PCNT
        {
            get { return concession_rule_concession_pcnt; }
            set { concession_rule_concession_pcnt = value; }
        }
        private string appt_no;
        public string APPT_NO
        {
            get { return appt_no; }
            set { appt_no = value; }
        }
        private string consultant_transfer_dt;
        public string CONSULTANT_TRANSFER_DT
        {
            get { return consultant_transfer_dt; }
            set { consultant_transfer_dt = value; }
        }

        private int _APT_PAT_ID;

        public int APT_PAT_ID
        {
            get { return _APT_PAT_ID; }
            set { _APT_PAT_ID = value; }
        }
        private string apmnt_id1;
        public string APMNT_ID1
        {
            get { return apmnt_id1; }
            set { apmnt_id1 = value; }
        }
        private int reg_corporate_id;

        public int REG_CORPORATE_ID
        {
            get { return reg_corporate_id; }
            set { reg_corporate_id = value; }
        }
        private string emp_grade_id;
        public string EMP_GRADE_ID
        {
            get { return emp_grade_id; }
            set { emp_grade_id = value; }
        }
        private string relationname;
        public string RelationName
        {
            get { return relationname; }
            set { relationname = value; }
        }
        private string emp_coverage_id;
        public string EMP_COVERAGE_ID
        {
            get { return emp_coverage_id; }
            set { emp_coverage_id = value; }
        }
        private string employeename;
        public string EmployeeName
        {
            get { return employeename; }
            set { employeename = value; }
        }
        private string department_name;
        public string Department_Name
        {
            get { return department_name; }
            set { department_name = value; }
        }
        private string branch_name;
        public string BRANCH_NAME
        {
            get { return branch_name; }
            set { branch_name = value; }
        }
        private string eligibal_ward_group_id;
        public string ELIGIBAL_WARD_GROUP_ID
        {
            get { return eligibal_ward_group_id; }
            set { eligibal_ward_group_id = value; }
        }
        private string comany_cd;
        public string COMANY_CD
        {
            get { return comany_cd; }
            set { comany_cd = value; }
        }
        private string valnoof_con;
        public string VALNOOF_CON
        {
            get { return valnoof_con; }
            set { valnoof_con = value; }
        }
        private string valnoofvisits;
        public string VALNOOFVISITS
        {
            get { return valnoofvisits; }
            set { valnoofvisits = value; }
        }
        private string apply_default_aol_confgn;
        public string APPLY_DEFAULT_AOL_CONFGN
        {
            get { return apply_default_aol_confgn; }
            set { apply_default_aol_confgn = value; }
        }
        private string valnoofdays;
        public string VALNOOFDAYS
        {
            get { return valnoofdays; }
            set { valnoofdays = value; }
        }
        private string org_percent;
        public string ORG_PERCENT
        {
            get { return org_percent; }
            set { org_percent = value; }
        }
        private string emp_percent;
        public string EMP_PERCENT
        {
            get { return emp_percent; }
            set { emp_percent = value; }
        }
        private string effect_from_dt;
        public string EFFECT_FROM_DT
        {
            get { return effect_from_dt; }
            set { effect_from_dt = value; }
        }
        private string effect_to_dt;
        public string EFFECT_TO_DT
        {
            get { return effect_to_dt; }
            set { effect_to_dt = value; }
        }
        private string color;
        public string COLOR
        {
            get { return color; }
            set { color = value; }
        }
        private int cons_tariff_id;
        public int CONS_TARIFF_ID
        {
            get { return cons_tariff_id; }
            set { cons_tariff_id = value; }
        }
        private string op_priority;
        public string OP_PRIORITY
        {
            get { return op_priority; }
            set { op_priority = value; }
        }
        private string op_priority_color_cds;
        public string OP_PRIORITY_COLOR_CDS
        {
            get { return op_priority_color_cds; }
            set { op_priority_color_cds = value; }
        }
        private string op_priority_tariffs;
        public string OP_PRIORITY_TARIFFS
        {
            get { return op_priority_tariffs; }
            set { op_priority_tariffs = value; }
        }
        private string consultation_disc_per;
        public string CONSULTATION_DISC_PER
        {
            get { return consultation_disc_per; }
            set { consultation_disc_per = value; }
        }
        private string company_desc;
        public string COMPANY_DESC
        {
            get { return company_desc; }
            set { company_desc = value; }
        }
        private string op_cons_payment;
        public string OP_CONS_PAYMENT
        {
            get { return op_cons_payment; }
            set { op_cons_payment = value; }
        }
        private string val_no_of_consultations;
        public string VAL_NO_OF_CONSULTATIONS
        {
            get { return val_no_of_consultations; }
            set { val_no_of_consultations = value; }
        }
        private string val_no_of_days;
        public string VAL_NO_OF_DAYS
        {
            get { return val_no_of_days; }
            set { val_no_of_days = value; }
        }
        private string colour_id;
        public string COLOUR_ID
        {
            get { return colour_id; }
            set { colour_id = value; }
        }
        private string department;
        public string DEPARTMENT
        {
            get { return department; }
            set { department = value; }
        }
        private string branch;
        public string BRANCH
        {
            get { return branch; }
            set { branch = value; }
        }
        public byte[] IMAGE { get; set; }
        private string cmp_cons_done;
        public string CMP_CONS_DONE
        {
            get { return cmp_cons_done; }
            set { cmp_cons_done = value; }
        }
        private string cmpy_referl_letter;
        public string CMPY_REFERL_LETTER
        {
            get { return cmpy_referl_letter; }
            set { cmpy_referl_letter = value; }
        }
        private string cmpy_referl_letter_days;
        public string CMPY_REFERL_LETTER_DAYS
        {
            get { return cmpy_referl_letter_days; }
            set { cmpy_referl_letter_days = value; }
        }
        private string credit_limit_amt_op;
        public string CREDIT_LIMIT_AMT_OP
        {
            get { return credit_limit_amt_op; }
            set { credit_limit_amt_op = value; }
        }
        private string is_conseligible_ward;
        public string IS_CONSELIGIBLE_WARD
        {
            get { return is_conseligible_ward; }
            set { is_conseligible_ward = value; }
        }
        private string tariff_configuration_ip;
        public string TARIFF_CONFIGURATION_IP
        {
            get { return tariff_configuration_ip; }
            set { tariff_configuration_ip = value; }
        }
        private string tariff_configuration_op;
        public string TARIFF_CONFIGURATION_OP
        {
            get { return tariff_configuration_op; }
            set { tariff_configuration_op = value; }
        }
        private string ip_approval_req_min_amt;
        public string IP_APPROVAL_REQ_MIN_AMT
        {
            get { return ip_approval_req_min_amt; }
            set { ip_approval_req_min_amt = value; }
        }
        private string tariff_name;
        public string TARIFF_NAME
        {
            get { return tariff_name; }
            set { tariff_name = value; }
        }
        private string ip_org_percent;
        public string IP_ORG_PERCENT
        {
            get { return ip_org_percent; }
            set { ip_org_percent = value; }
        }
        private string ip_emp_percent;
        public string IP_EMP_PERCENT
        {
            get { return ip_emp_percent; }
            set { ip_emp_percent = value; }
        }
        private string company_type_id;
        public string COMPANY_TYPE_ID
        {
            get { return company_type_id; }
            set { company_type_id = value; }
        }
        private string employee_desc1;
        public string EMPLOYEE_DESC1
        {
            get { return employee_desc1; }
            set { employee_desc1 = value; }
        }
        private string address11;
        public string Address11
        {
            get { return address11; }
            set { address11 = value; }
        }
        private string mobile_phone1;
        public string MOBILE_PHONE1
        {
            get { return mobile_phone1; }
            set { mobile_phone1 = value; }
        }
        private string sex;
        public string SEX
        {
            get { return sex; }
            set { sex = value; }
        }
        private string designation_name;
        public string DESIGNATION_NAME
        {
            get { return designation_name; }
            set { designation_name = value; }
        }
        private int designation_id;
        public int DESIGNATION_ID
        {
            get { return designation_id; }
            set { designation_id = value; }
        }
        private string office_phone;
        public string OFFICE_PHONE
        {
            get { return office_phone; }
            set { office_phone = value; }
        }
        private string umrn;
        public string UMRN
        {
            get { return umrn; }
            set { umrn = value; }
        }
        private int noofrecords;
        public int NoOfRecords
        {
            get { return noofrecords; }
            set { noofrecords = value; }
        }
        private string empcode;
        public string EmpCode
        {
            get { return empcode; }
            set { empcode = value; }
        }
        private string empdob;
        public string EmpDOB
        {
            get { return empdob; }
            set { empdob = value; }
        }
        private string empfathername;
        public string EmpFatherName
        {
            get { return empfathername; }
            set { empfathername = value; }
        }
        private string empfirstname;
        public string EmpFirstName
        {
            get { return empfirstname; }
            set { empfirstname = value; }
        }
        private string empjoiningdt;
        public string EmpJoiningDt
        {
            get { return empjoiningdt; }
            set { empjoiningdt = value; }
        }
        private string emplastname;
        public string EmpLastName
        {
            get { return emplastname; }
            set { emplastname = value; }
        }
        private string empmaritalstatus;
        public string EmpMaritalStatus
        {
            get { return empmaritalstatus; }
            set { empmaritalstatus = value; }
        }
        private string empmidname;
        public string EmpMidName
        {
            get { return empmidname; }
            set { empmidname = value; }
        }
        private string empnationality;
        public string EmpNationality
        {
            get { return empnationality; }
            set { empnationality = value; }
        }
        private string empsex;
        public string EmpSex
        {
            get { return empsex; }
            set { empsex = value; }
        }
        private string empbloodgroup;
        public string EmpBloodGroup
        {
            get { return empbloodgroup; }
            set { empbloodgroup = value; }
        }
        private string bill_type_name;
        public string BILL_TYPE_NAME
        {
            get { return bill_type_name; }
            set { bill_type_name = value; }
        }
        private string create_by_name;
        public string CREATE_BY_NAME
        {
            get { return create_by_name; }
            set { create_by_name = value; }
        }
        private string modify_by_name;
        public string MODIFY_BY_NAME
        {
            get { return modify_by_name; }
            set { modify_by_name = value; }
        }
        private string dischr_dt;
        public string DISCHR_DT
        {
            get { return dischr_dt; }
            set { dischr_dt = value; }
        }
        private string cmpny_referal_letter_id;
        public string CMPNY_REFERAL_LETTER_ID
        {
            get { return cmpny_referal_letter_id; }
            set { cmpny_referal_letter_id = value; }

        }
        private string patient_name;
        public string PATIENT_NAME
        {
            get { return patient_name; }
            set { patient_name = value; }
        }
        private string post_discount;
        public string POST_DISCOUNT
        {
            get { return post_discount; }
            set { post_discount = value; }
        }
        private string corp_dischr_dt;
        public string CORP_DISCHR_DT
        {
            get { return corp_dischr_dt; }
            set { corp_dischr_dt = value; }
        }
        private string phar_status;
        public string PHAR_STATUS
        {
            get { return phar_status; }
            set { phar_status = value; }
        }
        private string letter_issued_by;
        public string LETTER_ISSUED_BY
        {
            get { return letter_issued_by; }
            set { letter_issued_by = value; }
        }
        private string referral_letter_issue_dt;
        public string REFERRAL_LETTER_ISSUE_DT
        {
            get { return referral_letter_issue_dt; }
            set { referral_letter_issue_dt = value; }
        }
        private string referral_validity_dt;
        public string REFERRAL_VALIDITY_DT
        {
            get { return referral_validity_dt; }
            set { referral_validity_dt = value; }
        }
        private string patient_coverage_id;
        public string PATIENT_COVERAGE_ID
        {
            get { return patient_coverage_id; }
            set { patient_coverage_id = value; }
        }
        private string stmnt_done;
        public string STMNT_DONE
        {
            get { return stmnt_done; }
            set { stmnt_done = value; }
        }

        private string refrl_ltr_done;
        public string REFRL_LTR_DONE
        {
            get { return refrl_ltr_done; }
            set { refrl_ltr_done = value; }
        }
        private string total_credit_limit_amt;
        public string TOTAL_CREDIT_LIMIT_AMT
        {
            get { return total_credit_limit_amt; }
            set { total_credit_limit_amt = value; }
        }
        private string credit_limit_status;
        public string CREDIT_LIMIT_STATUS
        {
            get { return credit_limit_status; }
            set { credit_limit_status = value; }
        }
        private string is_credit_limit_unlimited;
        public string IS_CREDIT_LIMIT_UNLIMITED
        {
            get { return is_credit_limit_unlimited; }
            set { is_credit_limit_unlimited = value; }
        }
        private string remarks;
        public string REMARKS
        {
            get { return remarks; }
            set { remarks = value; }
        }
        private string relationship_name;
        public string RELATIONSHIP_NAME
        {
            get { return relationship_name; }
            set { relationship_name = value; }
        }
        private string utilized_amount;
        public string UTILIZED_AMOUNT
        {
            get { return utilized_amount; }
            set { utilized_amount = value; }
        }



    }
}
